// =====================================================
// JADEL CLINIC - Mock Data for Development
// =====================================================

import { Department, Doctor } from '@/types';

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: '1',
    name: 'General Medicine',
    slug: 'general-medicine',
    description: 'Comprehensive primary care and general health consultations',
    icon: 'Stethoscope',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Cardiology',
    slug: 'cardiology',
    description: 'Heart and cardiovascular system care',
    icon: 'Heart',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Neurology',
    slug: 'neurology',
    description: 'Brain and nervous system disorders',
    icon: 'Brain',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Orthopaedics',
    slug: 'orthopaedics',
    description: 'Bone, joint, and musculoskeletal care',
    icon: 'Bone',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Paediatrics',
    slug: 'paediatrics',
    description: 'Specialized care for infants, children, and adolescents',
    icon: 'Baby',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'ENT',
    slug: 'ent',
    description: 'Ear, Nose, and Throat care',
    icon: 'Ear',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Dermatology',
    slug: 'dermatology',
    description: 'Skin, hair, and nail conditions',
    icon: 'Sparkles',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Dental',
    slug: 'dental',
    description: 'Oral health and dental care',
    icon: 'Smile',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Laboratory',
    slug: 'laboratory',
    description: 'Diagnostic testing and analysis',
    icon: 'Microscope',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Radiology',
    slug: 'radiology',
    description: 'Medical imaging and diagnostics',
    icon: 'Scan',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Emergency',
    slug: 'emergency',
    description: '24/7 emergency medical services',
    icon: 'Siren',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Obstetrics',
    slug: 'obstetrics',
    description: 'Pregnancy, childbirth, and postpartum care',
    icon: 'BabyIcon',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Physiotherapy',
    slug: 'physiotherapy',
    description: 'Physical rehabilitation and therapy',
    icon: 'Activity',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_DOCTORS: Partial<Doctor>[] = [
  {
    id: '1',
    user_id: 'doc1',
    department_id: '1',
    license_number: 'MED-2015-001',
    specialization: 'General Medicine',
    qualification: 'MBBS, MD (Internal Medicine)',
    experience_years: 12,
    bio: 'Dr. Adebayo specializes in preventive care and chronic disease management. With over 12 years of experience, he has helped thousands of patients maintain optimal health through personalized treatment plans.',
    languages: ['English', 'Yoruba', 'Igbo'],
    consultation_fee: 15000,
    is_available: true,
    user: {
      id: 'doc1',
      email: 'adebayo@jadelclinic.demo',
      full_name: 'Dr. Adebayo Okonkwo',
      phone: '+234 803 456 7890',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Adebayo+Okonkwo&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '2',
    user_id: 'doc2',
    department_id: '2',
    license_number: 'MED-2012-045',
    specialization: 'Cardiology',
    qualification: 'MBBS, MD (Cardiology), FACC',
    experience_years: 15,
    bio: 'Dr. Chioma is a renowned cardiologist with extensive experience in treating heart conditions. She specializes in interventional cardiology and has performed over 500 successful cardiac procedures.',
    languages: ['English', 'Igbo'],
    consultation_fee: 25000,
    is_available: true,
    user: {
      id: 'doc2',
      email: 'chioma@jadelclinic.demo',
      full_name: 'Dr. Chioma Nwankwo',
      phone: '+234 805 123 4567',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Chioma+Nwankwo&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '3',
    user_id: 'doc3',
    department_id: '3',
    license_number: 'MED-2014-089',
    specialization: 'Neurology',
    qualification: 'MBBS, MD (Neurology)',
    experience_years: 10,
    bio: 'Dr. Ibrahim specializes in neurological disorders including epilepsy, stroke, and neurodegenerative diseases. He is passionate about improving the quality of life for his patients through advanced treatment methods.',
    languages: ['English', 'Hausa', 'French'],
    consultation_fee: 22000,
    is_available: true,
    user: {
      id: 'doc3',
      email: 'ibrahim@jadelclinic.demo',
      full_name: 'Dr. Ibrahim Musa',
      phone: '+234 807 234 5678',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Ibrahim+Musa&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '4',
    user_id: 'doc4',
    department_id: '4',
    license_number: 'MED-2013-056',
    specialization: 'Orthopaedics',
    qualification: 'MBBS, MS (Orthopaedics)',
    experience_years: 13,
    bio: 'Dr. Oluwaseun is an expert in joint replacement surgery and sports medicine. He has helped numerous athletes return to peak performance and elderly patients regain mobility through innovative surgical techniques.',
    languages: ['English', 'Yoruba'],
    consultation_fee: 20000,
    is_available: true,
    user: {
      id: 'doc4',
      email: 'oluwaseun@jadelclinic.demo',
      full_name: 'Dr. Oluwaseun Adeyemi',
      phone: '+234 809 345 6789',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Oluwaseun+Adeyemi&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '5',
    user_id: 'doc5',
    department_id: '5',
    license_number: 'MED-2016-023',
    specialization: 'Paediatrics',
    qualification: 'MBBS, MD (Paediatrics)',
    experience_years: 8,
    bio: 'Dr. Amina is dedicated to providing comprehensive care for children from infancy through adolescence. She specializes in developmental pediatrics and childhood nutrition.',
    languages: ['English', 'Hausa', 'Fulani'],
    consultation_fee: 18000,
    is_available: true,
    user: {
      id: 'doc5',
      email: 'amina@jadelclinic.demo',
      full_name: 'Dr. Amina Bello',
      phone: '+234 810 456 7890',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Amina+Bello&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '6',
    user_id: 'doc6',
    department_id: '6',
    license_number: 'MED-2015-078',
    specialization: 'ENT',
    qualification: 'MBBS, MS (ENT)',
    experience_years: 11,
    bio: 'Dr. Chukwuemeka specializes in ear, nose, and throat disorders. He has extensive experience in treating hearing loss, sinus problems, and performing minimally invasive ENT surgeries.',
    languages: ['English', 'Igbo'],
    consultation_fee: 19000,
    is_available: true,
    user: {
      id: 'doc6',
      email: 'chukwuemeka@jadelclinic.demo',
      full_name: 'Dr. Chukwuemeka Obi',
      phone: '+234 812 567 8901',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Chukwuemeka+Obi&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '7',
    user_id: 'doc7',
    department_id: '7',
    license_number: 'MED-2017-034',
    specialization: 'Dermatology',
    qualification: 'MBBS, MD (Dermatology)',
    experience_years: 7,
    bio: 'Dr. Folake is a skilled dermatologist specializing in both medical and cosmetic dermatology. She treats various skin conditions and is known for her expertise in acne treatment and anti-aging procedures.',
    languages: ['English', 'Yoruba'],
    consultation_fee: 21000,
    is_available: true,
    user: {
      id: 'doc7',
      email: 'folake@jadelclinic.demo',
      full_name: 'Dr. Folake Akinwale',
      phone: '+234 813 678 9012',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Folake+Akinwale&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '8',
    user_id: 'doc8',
    department_id: '8',
    license_number: 'MED-2014-067',
    specialization: 'Dentistry',
    qualification: 'BDS, MDS (Conservative Dentistry)',
    experience_years: 12,
    bio: 'Dr. Emeka is an experienced dentist specializing in restorative and cosmetic dentistry. He is passionate about helping patients achieve healthy, beautiful smiles through modern dental techniques.',
    languages: ['English', 'Igbo'],
    consultation_fee: 17000,
    is_available: true,
    user: {
      id: 'doc8',
      email: 'emeka@jadelclinic.demo',
      full_name: 'Dr. Emeka Okoro',
      phone: '+234 814 789 0123',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Emeka+Okoro&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '9',
    user_id: 'doc9',
    department_id: '11',
    license_number: 'MED-2011-012',
    specialization: 'Emergency Medicine',
    qualification: 'MBBS, MD (Emergency Medicine)',
    experience_years: 14,
    bio: 'Dr. Funmilayo leads our emergency department with over 14 years of experience in critical care. She has managed thousands of emergency cases and is certified in advanced trauma life support.',
    languages: ['English', 'Yoruba'],
    consultation_fee: 0,
    is_available: true,
    user: {
      id: 'doc9',
      email: 'funmilayo@jadelclinic.demo',
      full_name: 'Dr. Funmilayo Adebisi',
      phone: '+234 815 890 1234',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Funmilayo+Adebisi&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '10',
    user_id: 'doc10',
    department_id: '12',
    license_number: 'MED-2013-089',
    specialization: 'Obstetrics & Gynaecology',
    qualification: 'MBBS, MD (OB/GYN)',
    experience_years: 13,
    bio: 'Dr. Ngozi specializes in women\'s health, pregnancy, and childbirth. She has successfully delivered over 2000 babies and is known for her compassionate care for expectant mothers.',
    languages: ['English', 'Igbo'],
    consultation_fee: 23000,
    is_available: true,
    user: {
      id: 'doc10',
      email: 'ngozi@jadelclinic.demo',
      full_name: 'Dr. Ngozi Eze',
      phone: '+234 816 901 2345',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Ngozi+Eze&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '11',
    user_id: 'doc11',
    department_id: '13',
    license_number: 'MED-2016-045',
    specialization: 'Physiotherapy',
    qualification: 'BPT, MPT (Sports Physiotherapy)',
    experience_years: 9,
    bio: 'Dr. Tunde is a sports physiotherapist with expertise in rehabilitation and injury prevention. He has worked with professional athletes and helps patients recover from musculoskeletal injuries.',
    languages: ['English', 'Yoruba'],
    consultation_fee: 16000,
    is_available: true,
    user: {
      id: 'doc11',
      email: 'tunde@jadelclinic.demo',
      full_name: 'Dr. Tunde Bakare',
      phone: '+234 817 012 3456',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Tunde+Bakare&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '12',
    user_id: 'doc12',
    department_id: '10',
    license_number: 'MED-2015-092',
    specialization: 'Radiology',
    qualification: 'MBBS, MD (Radiology)',
    experience_years: 11,
    bio: 'Dr. Yusuf is an expert radiologist specializing in diagnostic imaging. He utilizes cutting-edge technology including MRI, CT scans, and ultrasound to provide accurate diagnoses for complex medical conditions.',
    languages: ['English', 'Hausa', 'Arabic'],
    consultation_fee: 20000,
    is_available: true,
    user: {
      id: 'doc12',
      email: 'yusuf@jadelclinic.demo',
      full_name: 'Dr. Yusuf Abdullahi',
      phone: '+234 818 123 4567',
      role: 'doctor',
      avatar_url: 'https://ui-avatars.com/api/?name=Yusuf+Abdullahi&background=3b82f6&color=fff',
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
];
